# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Huaming Chen
title: "Dada" of Chen, a researcher, a developer & a basketballer
email: Your email (optional)

email: huaming.chen@sydney.edu.au; huaming.chen@ieee.org
phone: +61 2 8627 0387
website: https://huaming-chen.com

#Social links
googlescholar_username: 3-qRVLUAAAAJ
# twitter_username: favorming
linkedin_username: huaming-chen
publons_username: huaming-chen

#About Section
about_title: About Me (Use this to override about section title)
about_profile_image: /images/Huaming_Chen.jpg
about_content: | # this will include new lines to allow paragraphs
  Greetings!
  ---
  My name is Huaming Chen. I am currently a lecturer (assistant professor) in University of Sydney. Prior joining USYD, I was a research fellow in University of Adelaide. I received my Ph.D degree from School of Computing and Information Technology in University of Wollongong, Australia. I received my Master and Bachelor degrees from DSLab and Honors Class at Lanzhou University.

  ---
  "Study without desire spoils the memory, and it retains nothing that it takes in.â€ 
  -- Leonardo da Vinci
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-83702637-1

# More Section
more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  ---
#  I am interested in the intersection research of machine learning and biology systems. I am honored to be under the supervision of A/Prof. Jun Shen, A/Prof. Lei Wang, A/Prof. Jiangning Song and Dr. Chi-Hung Chi for my Ph.D study, who have given me valuable opportunities in research and help me learning in an expotential growth curve from both machine learning and biology areas. I have been honored to visit NICE group led by Prof. Yaochu Jin in University of Surrey during my Ph.D session.
#  Prior to my Ph.D session, it was my great fortune to work in DSLab leading by Prof. Zhou. I have worked with Prof. Nicholas Mc Guire in the topic of Linux kernel development, focusing on real-time linux kernel, also I have worked with Prof. Hong Zhao in the topic of neural network in the final year of master session.
#  A wide area covering from the lower-level computer architecture, such as real-time Linux kernel development, driver development and computer operating systems, to the higher-level algorithms and statistical models including artificial intelligence, machine learning and bioinformatics, has been through my learning and practicing career. Relevant projects and publications can be found attached.
  At this stage, I focus on the topic of software security, especially for AI-enabled systems. Particularly, a call on securing the AI-enabled systems in practice with dedicated software engineering techniques is a brief summary to my current work.
  Generally, I am also passionate in the research areas driven by artificial intelligence (AI for software engineering and science), such as software security, industrial 4.0, computational biology and so on. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]